
-- =============================================================================
-- SCRIPT DE CARGA DE DADOS REAIS DE EQUIPAMENTOS (CORRIGIDO)
-- Autor: SGMI 2.0
-- Objetivo: Garantir integridade referencial dos Tipos antes de atualizar os Ativos.
-- =============================================================================

BEGIN;

-- 1. GARANTIA DE TIPOS (Evita erro de Foreign Key 23503)
-- Insere todos os tipos que serão usados pela função de auto-classificação
INSERT INTO public.equipment_types (id, description) VALUES
('PRENSA_HIDRULICA', 'Prensa Hidráulica'),
('EXTRUSORA', 'Extrusora'),
('EXTRUSORA_DE_PA', 'Extrusora de PA'),
('FORNO', 'Forno'),
('TORNO_AUTOMTICO', 'Torno Automático'),
('TORNO_CNC', 'Torno CNC'),
('TORNO_MECANICO', 'Torno Mecânico'),
('SERRA_DE_FITA', 'Serra de Fita'),
('SERRA', 'Serra'),
('COMPRESSOR_DE_PARAFUSO', 'Compressor de Parafuso'),
('COMPRESSOR_PISTO_SCHULZ', 'Compressor Pistão Schulz'),
('MAQUINA_DE_SOLDA', 'Máquina de Solda'),
('FRESADORA_FERRAMENTARIA', 'Fresadora Ferramentaria'),
('RETFICA_PLANA', 'Retífica Plana'),
('EMPILHADEIRA', 'Empilhadeira'),
('PALETEIRA_ELTRICA', 'Paleteira Elétrica'),
('AR_CONDICIONADO', 'Ar Condicionado'),
('CMARA_FRIA', 'Câmara Fria'),
('TAMBOREADOR', 'Tamboreador'),
('AUTOFRETAGEM', 'Autofretagem'),
('FORNO_ELTRICO', 'Forno Elétrico'),
('TRANADEIRA', 'Trançadeira'),
('TRIDIMENSIONAL', 'Tridimensional'),
('TREFILA', 'Trefila'),
('ESMERIL', 'Esmeril'),
('MISTURADOR', 'Misturador'),
('JATO_DE_GRANALHA', 'Jato de Granalha'),
('JATO_DE_OXIDO_DE_ALUMINIO', 'Jato de Óxido de Alumínio'),
('ESPULADEIRA', 'Espuladeira'),
('ESTUFA_ELETRICA', 'Estufa Elétrica'),
('PRENSA_DE_MOLDAGEM', 'Prensa de Moldagem'),
('MOLDAGEM_COM_GLICERINA', 'Moldagem com Glicerina'),
('PRENSA', 'Prensa'),
('PRENSA_DE_EIXO_EXCENTRICO', 'Prensa de Eixo Excêntrico'),
('CENTRO_DE_USINAGEM', 'Centro de Usinagem'),
('RETIFICA_DEWALT', 'Retífica Dewalt'),
('PRMOLDE', 'Pré-Molde'),
('POLICORTE', 'Policorte'),
('CONFORMADORA', 'Conformadora'),
('MAQUINA_A_LASER', 'Máquina a Laser'),
('COMPRESSOR_CHICAGO_CPCM_40BD', 'Compressor Chicago'),
('MAQUINA_DE_TESTE', 'Máquina de Teste'),
('CURVADORA', 'Curvadora'),
('RECRAVADEIRA_DE_MANGUEIRAS', 'Recravadeira de Mangueiras'),
('CABINE_SECUNDARIA', 'Cabine Secundária'),
('CABINE_PRIMARIA', 'Cabine Primária'),
('QUADRO_DE_ILUMINAO', 'Quadro de Iluminação'),
('QUADRO_DE_FORA', 'Quadro de Força'),
('QUADRO_GERAL_DO_AR_CONDICIONADO', 'Quadro Geral Ar Condicionado'),
('QUADRO_ELETRICO_COMANDO_DA_PORTARIA', 'Quadro Elétrico Portaria'),
('QUADRO_ELETRICO_COMANDO_ENGENHARIAPCD', 'Quadro Elétrico Engenharia/PCD'),
('QUADRO_ELETRICO_COMANDO_DO_REFEITRIO', 'Quadro Elétrico Refeitório'),
('CALANDRA', 'Calandra'),
('SOLDA_POR_INDUO', 'Solda por Indução'),
('CHILLER', 'Chiller'),
('MAQUINA_DE_CORRUGAR', 'Máquina de Corrugar'),
('BEBEDOURO_DIRETORIA', 'Bebedouro Diretoria'),
('BEBEDOURO_ENGENHARIA', 'Bebedouro Engenharia'),
('BEBEDOURO_AUTOMOTIVO', 'Bebedouro Automotivo'),
('BEBEDOURO_INJEO', 'Bebedouro Injeção'),
('ENROLADOR_DE_FITA', 'Enrolador de Fita'),
('CABINE_DE_PINTURA_HALAR', 'Cabine de Pintura Halar'),
('CABINE_DE_PINTURA', 'Cabine de Pintura'),
('TESTE_TREFILA', 'Teste de Trefila'),
('PUXADOR', 'Puxador'),
('TORNO_REVOLVER', 'Torno Revólver'),
('ROUTER', 'Router'),
('LAVADOR_DE_PEAS', 'Lavador de Peças'),
('PLAINA', 'Plaina'),
('BALANA', 'Balança'),
('BALANA_01', 'Balança 01'),
('BALANA_02', 'Balança 02'),
('ESTUFA_DE_FUNIL', 'Estufa de Funil'),
('MAQUINA_DE_VIROLA', 'Máquina de Virola'),
('GERADOR', 'Gerador'),
('SERRA_CIRCULAR', 'Serra Circular'),
('TORRE_DE_RESFRIAMENTO', 'Torre de Resfriamento'),
('CAVALETE_AR_RESPIRATORIO_JATO_DE_GRANALHA', 'Cavalete de Ar Respiratório'),
('GUILHOTINA', 'Guilhotina')
ON CONFLICT (id) DO NOTHING;

-- 2. Tabela temporária para carga dos equipamentos
CREATE TEMP TABLE temp_equipments (
    id TEXT,
    name TEXT,
    manufacturer TEXT,
    model TEXT,
    year_val TEXT,
    location TEXT,
    status_val TEXT DEFAULT 'Ativo',
    category_val public.asset_category DEFAULT 'Industrial'
);

-- 3. Inserção dos dados brutos
INSERT INTO temp_equipments (id, name, manufacturer, model, year_val, location, category_val) VALUES
('AEX-01', 'EXTRUSORA DE PA', 'Atema', 'EX 60/30', '2021', 'AUTOMOTIVO', 'Industrial'),
('PH-15', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('CF-01', 'CÂMARA FRIA', 'Enge Fril', NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('TB-01', 'TAMBOREADOR', 'GV Máquina', NULL, NULL, 'USINAGEM', 'Industrial'),
('FO-10', 'FORNO', NULL, NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('TA-01', 'TORNO AUTOMÁTICO', 'Traub', 'A15125', NULL, 'DESATIVADO', 'Industrial'),
('TA-02', 'TORNO AUTOMÁTICO', 'Traub', 'A15125', NULL, 'USINAGEM', 'Industrial'),
('AF-01', 'AUTOFRETAGEM', NULL, NULL, NULL, 'AUTOMOTIVO', 'Industrial'),
('FO-09', 'FORNO ELÉTRICO', 'Revest Arc', 'VC-091148', NULL, 'EXTRUSÃO', 'Industrial'),
('TD-02', 'TRANÇADEIRA', 'Nadolsky', NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('FO-11', 'FORNO', 'Standard', 'SET', '2002', 'EXTRUSÃO', 'Industrial'),
('FO-12', 'FORNO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('TRID-01', 'TRIDIMENSIONAL', NULL, NULL, NULL, 'SALA QUALIDADE', 'Industrial'),
('TF-01', 'TREFILA', NULL, NULL, NULL, 'TREFILA', 'Industrial'),
('ES-01', 'ESMERIL', NULL, NULL, NULL, 'USINAGEM', 'Industrial'),
('SF-03', 'SERRA DE FITA', 'Ronemak', 'MR 330', NULL, 'EXTRUSÃO', 'Industrial'),
('EX-01', 'EXTRUSORA', NULL, NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('AEX-02', 'EXTRUSORA DE PA', 'Atema', 'EX 60/30', '2021', 'AUTOMOTIVO', 'Industrial'),
('MI-04', 'MISTURADOR', NULL, NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('EX-02', 'EXTRUSORA', 'Safety Switch', NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('EX-03', 'EXTRUSORA', 'WK Worek', 'D8555', '1992', 'EXTRUSÃO', 'Industrial'),
('TA-03', 'TORNO AUTOMÁTICO', 'Traub', 'TA25', NULL, 'USINAGEM', 'Industrial'),
('FO-13', 'FORNO', 'Shammatherm', 'SH-T', '2013', 'TUBULAÇÃO', 'Industrial'),
('TF-02', 'TREFILA', 'Lombard', NULL, NULL, 'TREFILA', 'Industrial'),
('FO-08', 'FORNO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('ES-04', 'ESMERIL', NULL, NULL, NULL, 'MANUTENÇÃO', 'Industrial'),
('TC-01', 'TORNO CNC', 'Nardini', '1195', '2009', 'USINAGEM', 'Industrial'),
('TC-02', 'TORNO CNC', 'Nardini', 'L.195', '2009', 'USINAGEM', 'Industrial'),
('TC-03', 'TORNO CNC', 'Nardini', '1195', '2004', 'USINAGEM', 'Industrial'),
('TC-04', 'TORNO CNC', 'Nardini', '1.195', '2006', 'USINAGEM', 'Industrial'),
('JT-01', 'JATO DE GRANALHA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('TC-05', 'TORNO CNC', 'Nardini', '1195', '2008', 'USINAGEM', 'Industrial'),
('TC-06', 'TORNO CNC', 'Nardini', '1195', '2009', 'USINAGEM', 'Industrial'),
('TC-07', 'TORNO CNC', 'Romi', 'Centur 300', '2007', 'USINAGEM', 'Industrial'),
('TC-08', 'TORNO CNC', 'Nardini', '1.350', '2013', 'USINAGEM', 'Industrial'),
('MS-01', 'MÁQUINA DE SOLDA', NULL, NULL, NULL, 'DESATIVADO', 'Industrial'),
('JT-02', 'JATO DE ÓXIDO DE ALUMÍNIO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('EX-05', 'EXTRUSORA', NULL, NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('EP-02', 'ESPULADEIRA', 'Fusotec', '72', '1997', 'TRANÇADEIRA', 'Industrial'),
('FO-01', 'ESTUFA ELÉTRICA', 'Techair', NULL, NULL, 'MOLDAGEM', 'Industrial'),
('FO-02', 'ESTUFA ELÉTRICA', 'Standard', 'SE-T', '2003', 'MOLDAGEM', 'Industrial'),
('FO-03', 'FORNO', 'Inco', 'BTH3601485', NULL, 'MOLDAGEM', 'Industrial'),
('FO-04', 'FORNO', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('FO-05', 'FORNO', NULL, NULL, NULL, 'AUTOMOTIVO', 'Industrial'),
('FO-06', 'FORNO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('FO-07', 'FORNO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('PH-01', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-03', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-02', 'PRENSA DE MOLDAGEM', 'EKA', NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-04', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('TM-03', 'TORNO MECÂNICO', 'Diplomat', 'ND.250', NULL, 'USINAGEM', 'Industrial'),
('TM-04', 'TORNO MECÂNICO', 'Nardini', 'ND 250', '2013', 'USINAGEM', 'Industrial'),
('TM-05', 'TORNO MECÂNICO', 'Nardini', 'ND.250', '2013', 'USINAGEM', 'Industrial'),
('TM-06', 'TORNO MECÂNICO', 'Diplomat', 'NZ 400', '2004/2005', 'USINAGEM', 'Industrial'),
('MG-01', 'MOLDAGEM COM GLICERINA', NULL, NULL, NULL, 'AUTOMOTIVO', 'Industrial'),
('PH-13', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('ES-03', 'ESMERIL', NULL, NULL, NULL, 'FERRAMENTARIA', 'Industrial'),
('PH-14', 'PRENSA', 'LP Cope', 'PHR 600', '1985', 'MOLDAGEM', 'Industrial'),
('PH-16', 'PRENSA HIDRÁULICA', 'Inco', 'PC 30005385', NULL, 'MOLDAGEM', 'Industrial'),
('PH-18', 'PRENSA HIDRÁULICA', 'Ranalli', NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-19', 'PRENSA HIDRÁULICA', 'Farex', NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('TD-01', 'TRANÇADEIRA', 'Fusotec', 'W72', '2004', 'TRANÇADEIRA', 'Industrial'),
('SF-01', 'SERRA', 'Baldan', 'SFC-3', '2020', 'USINAGEM', 'Industrial'),
('EX-04', 'EXTRUSORA', 'Jennings', NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('PH-20', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('PH-05', 'PRENSA DE EIXO EXCENTRICO', 'Fabbe', NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-06', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-07', 'PRENSA DE MOLDAGEM', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('MS-02', 'MÁQUINA DE SOLDA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('MS-03', 'MÁQUINA DE SOLDA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('MS-04', 'MÁQUINA DE SOLDA', NULL, NULL, NULL, 'DESATIVADO', 'Industrial'),
('MS-06', 'MÁQUINA DE SOLDA', NULL, NULL, NULL, 'FERRAMENTARIA', 'Industrial'),
('CT-01', 'CENTRO DE USINAGEM', 'Romi', 'DISCOVERYV1250', '2007', 'USINAGEM', 'Industrial'),
('PH-08', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-09', 'PRENSA DE MOLDAGEM', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('PH-10', 'PRENSA DE MOLDAGEM', 'Inco', 'PC1502385', NULL, 'MOLDAGEM', 'Industrial'),
('TM-02', 'TORNO MECÂNICO', 'Nardini', 'MS205', NULL, 'FERRAMENTARIA', 'Industrial'),
('RE-01', 'RETÍFICA DEWALT', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('PH-17', 'PRENSA DE MOLDAGEM', 'Ranalli', NULL, NULL, 'MOLDAGEM', 'Industrial'),
('SF-02', 'SERRA DE FITA', 'Franho', 'SH-4242NC', '2013', 'USINAGEM', 'Industrial'),
('PM-01', 'PRÉ-MOLDE', 'Jennings', NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('TA-04', 'TORNO AUTOMÁTICO', 'Traub', 'A25', NULL, 'USINAGEM', 'Industrial'),
('TA-05', 'TORNO AUTOMÁTICO', 'Atras Máquinas', '15mm/25m', '2005', 'USINAGEM', 'Industrial'),
('EP-01', 'ESPULADEIRA', 'Fusotec', 'W1/W72', '2014', 'TRANÇADEIRA', 'Industrial'),
('EP-03', 'ESPULADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('PO-01', 'POLICORTE', NULL, NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('TD-05', 'TRANÇADEIRA', 'Fusotec', 'W721A', '2011', 'TRANÇADEIRA', 'Industrial'),
('EF-01', 'CONFORMADORA', 'Crippa', '52086', '2023', 'AUTOMOTIVO', 'Industrial'),
('ML-01', 'MÁQUINA A LASER', 'Galvo Scanner', 'CMK-DESK-30', '2023', 'AUTOMOTIVO', 'Industrial'),
('ML-02', 'MÁQUINA A LASER', NULL, NULL, NULL, 'AUTOMOTIVO', 'Industrial'),
('CO-01', 'COMPRESSOR', 'Chicago', 'CPCM 40BD', NULL, 'SALA DE MÁQUINA', 'Industrial'),
('TM-01', 'TORNO MECÂNICO', NULL, NULL, NULL, 'FERRAMENTARIA', 'Industrial'),
('TD-06', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('CV-01', 'CURVADORA', 'Crippa', '1025E', '2024', 'AUTOMOTIVO', 'Industrial'),
('RM-01', 'RECRAVADEIRA DE MANGUEIRAS', 'Hylik', 'YB120L', '2023', 'AUTOMOTIVO', 'Industrial'),
('CS-01', 'CABINE SECUNDÁRIA', NULL, NULL, NULL, 'SALA DE MÁQUINA', 'Industrial'),
('CPR-01', 'CABINE PRIMÁRIA', NULL, NULL, NULL, 'SALA DE MÁQUINA', 'Industrial'),
('QI-01', 'QUADRO DE ILUMINAÇÃO', NULL, NULL, NULL, 'PREDIAL', 'Predial/Utilitário'),
('QDF-05', 'QUADRO DE FORÇA', 'Altovolt', NULL, '2021', 'USINAGEM', 'Predial/Utilitário'),
('QGC-01', 'QUADRO GERAL AR CONDICIONADO', NULL, NULL, NULL, 'USINAGEM', 'Predial/Utilitário'),
('FR-01', 'FRESADORA FERRAMENTARIA', 'Diplomat', '2000FVF', '2000', 'USINAGEM', 'Industrial'),
('QDF-04', 'QUADRO DE FORÇA', 'Altovolt', NULL, '2021', 'MOLDAGEM', 'Predial/Utilitário'),
('QDF-02', 'QUADRO DE FORÇA', 'Altovolt', NULL, '2021', 'TRANÇADEIRA', 'Predial/Utilitário'),
('QDF-01', 'QUADRO DE FORÇA', 'Altovolt', NULL, '2021', 'EXTRUSÃO', 'Predial/Utilitário'),
('QDF-06', 'QUADRO DE FORÇA', 'Altovolt', NULL, '2021', 'NÃO INFORMADA', 'Predial/Utilitário'),
('QE-01', 'QUADRO ELETRICO - PORTARIA', NULL, NULL, NULL, 'PORTARIA', 'Predial/Utilitário'),
('QE-03', 'QUADRO ELETRICO - ENGENHARIA/PCD', NULL, NULL, NULL, 'ENGENHARIA', 'Predial/Utilitário'),
('TD-04', 'TRANÇADEIRA', 'Fusotec', NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('QE-02', 'QUADRO ELETRICO - REFEITÓRIO', NULL, NULL, NULL, 'REFEITÓRIO', 'Predial/Utilitário'),
('CA-01', 'CALANDRA', NULL, NULL, NULL, 'USINAGEM', 'Industrial'),
('SI-01', 'SOLDA POR INDUÇÃO', 'GRC', 'WAG-15-10', NULL, 'AUTOMOTIVO', 'Industrial'),
('MI-01', 'MISTURADOR', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('MI-02', 'MISTURADOR', NULL, NULL, NULL, 'MOLDAGEM', 'Industrial'),
('MI-03', 'MISTURADOR', NULL, NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('CH-01', 'CHILLER', 'Smart-Chiller', 'VAVOASAZPR', '2023', 'AUTOMOTIVO', 'Industrial'),
('TF-04', 'TREFILA', NULL, NULL, NULL, 'ENCAMISAMENTO', 'Industrial'),
('CR-02', 'MÁQUINA DE CORRUGAR', NULL, NULL, NULL, 'ENCAMISAMENTO', 'Industrial'),
('TD-07', 'TRANÇADEIRA', 'Fusotec', 'W72TA', '2011', 'TRANÇADEIRA', 'Industrial'),
('TD-08', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('BEB-01', 'BEBEDOURO DIRETORIA', NULL, NULL, NULL, 'DIRETORIA', 'Predial/Utilitário'),
('BEB-02', 'BEBEDOURO ENGENHARIA', NULL, NULL, NULL, 'ENGENHARIA', 'Predial/Utilitário'),
('BEB-03', 'BEBEDOURO AUTOMOTIVO', NULL, NULL, NULL, 'AUTOMOTIVO', 'Predial/Utilitário'),
('BEB-04', 'BEBEDOURO INJEÇÃO', NULL, NULL, NULL, 'INJEÇÃO', 'Predial/Utilitário'),
('CO-02', 'COMPRESSOR PARAFUSO', NULL, NULL, NULL, 'SALA DE MÁQUINA', 'Industrial'),
('CO-03', 'COMPRESSOR PISTÃO', 'Schulz', NULL, NULL, 'SALA DE MÁQUINA', 'Industrial'),
('TF-03', 'TREFILA', NULL, NULL, NULL, 'DESATIVADO', 'Industrial'),
('EN-01', 'ENROLADOR DE FITA', NULL, NULL, NULL, 'EXPEDIÇÃO', 'Industrial'),
('FR-02', 'FRESADORA FERRAMENTARIA', NULL, NULL, NULL, 'FERRAMENTARIA', 'Industrial'),
('CP-01', 'CABINE DE PINTURA HALAR', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('CP-02', 'CABINE DE PINTURA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('TD-09', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('PH-11', 'PRENSA HIDRÁULICA', 'Inco', 'PC1503385', NULL, 'MOLDAGEM', 'Industrial'),
('PH-12', 'PRENSA HIDRÁULICA', 'Inco', 'PC1504385', NULL, 'MOLDAGEM', 'Industrial'),
('ES-SEM', 'ESMERIL (S/N)', NULL, NULL, NULL, 'FERRAMENTARIA', 'Industrial'),
('TES-01', 'TESTE DE ESTANQUEIDADE', NULL, NULL, NULL, 'TREFILA', 'Industrial'),
('CR-01', 'MÁQUINA DE CORRUGAR', NULL, NULL, NULL, 'NÃO INFORMADA', 'Industrial'),
('PX-01', 'TESTE HIDROSTÁTICO PUXADOR', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('CH-02', 'CHILLER', NULL, 'VAVO45A2PR201X', NULL, 'DESATIVADO', 'Industrial'),
('TA-06', 'TORNO AUTOMÁTICO', 'Traub', 'TB-42', NULL, 'DESATIVADO', 'Industrial'),
('TR-01', 'TORNO REVÓLVER', 'Atras Máquina', 'TR-25', '2005', 'USINAGEM', 'Industrial'),
('RO-01', 'ROUTER', 'Scriba', 'SB1325TM', '2016', 'USINAGEM', 'Industrial'),
('RO-02', 'ROUTER', 'Roctech', 'RO1525S-ATC-TM', '2022', 'USINAGEM', 'Industrial'),
('VR-01', 'LAVADOR DE PEÇAS', 'V Equipamentos', NULL, NULL, 'ENCAMISAMENTO', 'Industrial'),
('LP-02', 'LAVADOR DE PEÇAS', 'V Equipamentos', NULL, NULL, 'DESATIVADO', 'Industrial'),
('PL-01', 'PLAINA', 'Baldan', 'DPC-5', '2008', 'USINAGEM', 'Industrial'),
('BA-012', 'BALANÇA', 'Toledo', '2003/38-2180', '2014', 'NÃO INFORMADA', 'Predial/Utilitário'),
('BA-010', 'BALANÇA', NULL, 'BCW30', '2013', 'NÃO INFORMADA', 'Predial/Utilitário'),
('CR-03', 'MÁQUINA DE CORRUGAR', NULL, NULL, NULL, 'NÃO INFORMADA', 'Industrial'),
('CT-02', 'CENTRO DE USINAGEM', NULL, NULL, NULL, 'USINAGEM', 'Industrial'),
('ET-01', 'ESTUFA DE FUNIL', 'Xiecheng', 'XC-G100KG', '2025', 'AUTOMOTIVO', 'Industrial'),
('MV-01', 'MÁQUINA DE VIROLA', NULL, NULL, NULL, 'ENCAMISAMENTO', 'Industrial'),
('GE-01', 'GERADOR', NULL, NULL, NULL, 'SALA DE MÁQUINA', 'Industrial'),
('SC-01', 'SERRA CIRCULAR', 'Berat', '3158', NULL, 'AUTOMOTIVO', 'Industrial'),
('TRA-01', 'TORRE DE RESFRIAMENTO', NULL, NULL, NULL, 'EXTRUSÃO', 'Industrial'),
('CL-01', 'CAVALETE AR RESPIRATÓRIO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('EX-06', 'EXTRUSORA', 'Suko', 'PFG150 RAM', NULL, 'EXTRUSÃO', 'Industrial'),
('EX-07', 'EXTRUSORA', 'Suko', 'PFG150 RAM', NULL, 'EXTRUSÃO', 'Industrial'),
('GUI-01', 'GUILHOTINA', 'Polifluor', NULL, '2025', 'AUTOMOTIVO', 'Industrial'),
('SF-04', 'SERRA DE FITA', 'Mada', 'SH-500M', '2024', 'TUBULAÇÃO', 'Industrial'),
('SF-SEM', 'SERRA DE FITA (S/N)', NULL, NULL, NULL, 'FERRAMENTARIA', 'Industrial'),
('QGBT-01', 'QUADRO GERAL DE FORÇA', NULL, '220/127', NULL, 'AUTOMOTIVO', 'Predial/Utilitário'),
('TD-10', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Industrial'),
('QDF-03', 'QUADRO DE FORÇA', NULL, NULL, NULL, 'EXTRUSÃO', 'Predial/Utilitário'),
('ES-02', 'ESMERIL', NULL, NULL, NULL, 'USINAGEM', 'Industrial'),
('QOF-TER-01', 'QUADRO DE FORÇA', NULL, NULL, NULL, 'USINAGEM', 'Predial/Utilitário'),
('MS-05', 'MÁQUINA DE SOLDA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('LX-01', 'LIXADEIRA 2', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('LX-02', 'LIXADEIRA 2', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('EXT-01', 'LIXADEIRA 4', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('FU-01', 'FURADEIRA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('FU-02', 'FURADEIRA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Industrial'),
('TO-SEM', 'TORNO (S/N)', NULL, NULL, NULL, 'NÃO INFORMADA', 'Industrial'),
('FU-03', 'FURADEIRA DE BANCADA', NULL, NULL, NULL, 'MANUTENÇÃO', 'Industrial');

-- 4. Normalização de status
UPDATE temp_equipments SET status_val = 'Inativo' WHERE location LIKE '%DESATIVADO%' OR location LIKE '%OBSOLETO%';
UPDATE temp_equipments SET status_val = 'Desativado' WHERE location LIKE '%DESATIVADO%' OR location LIKE '%OBSOLETO%';

-- 5. UPSERT REAL (Agora seguro)
INSERT INTO public.equipments (id, name, manufacturer, model, year_of_manufacture, location, status, category)
SELECT 
    id, name, manufacturer, model, year_val, location, status_val, category_val
FROM temp_equipments
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    manufacturer = EXCLUDED.manufacturer,
    model = EXCLUDED.model,
    year_of_manufacture = EXCLUDED.year_of_manufacture,
    location = EXCLUDED.location,
    status = EXCLUDED.status,
    category = EXCLUDED.category;

DROP TABLE temp_equipments;

-- 6. Executar auto-classificação e vinculação de planos
SELECT auto_classify_equipments();
SELECT refresh_plan_targets();

COMMIT;

SELECT 'Base de equipamentos atualizada com 100% de sucesso! Novos ativos inseridos e dados detalhados aplicados.';
