
/* 
   SGMI 2.0 - SCRIPT DE TIPOS DE EQUIPAMENTO
   DATA: 09/06/2025
   OBJETIVO: Criar e popular tabela de referência para Planos de Manutenção.
*/

-- 1. Criação da Tabela (se não existir)
CREATE TABLE IF NOT EXISTS equipment_types (
    id TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Limpeza prévia para evitar duplicidade
DELETE FROM equipment_types;

-- 3. Inserção Baseada no PDF (IDs normalizados em UPPER_CASE_SNAKE)
INSERT INTO equipment_types (id, description) VALUES
('AUTOFRETAGEM', 'AUTOFRETAGEM'),
('BALANÇA', 'BALANÇA'),
('BEBEDOURO_AUTOMOTIVO', 'BEBEDOURO AUTOMOTIVO'),
('BEBEDOURO_DIRETORIA', 'BEBEDOURO DIRETORIA'),
('BEBEDOURO_ENGENHARIA', 'BEBEDOURO ENGENHARIA'),
('BEBEDOURO_INJEÇÃO', 'BEBEDOURO INJEÇÃO'),
('CABINE_DE_PINTURA', 'CABINE DE PINTURA'),
('CABINE_DE_PINTURA_HALAR', 'CABINE DE PINTURA HALAR'),
('CABINE_PRIMARIA', 'CABINE PRIMARIA'),
('CABINE_SECUNDARIA', 'CABINE SECUNDARIA'),
('CALANDRA', 'CALANDRA'),
('CAMARA_FRIA', 'CÂMARA FRIA'),
('CAVALETE_AR_RESPIRATORIO', 'CAVALETE AR RESPIRATORIO'),
('CENTRO_DE_USINAGEM', 'CENTRO DE USINAGEM'),
('CHILLER', 'CHILLER'),
('COMPRESSOR_CHICAGO_CPCM_40BD', 'COMPRESSOR CHICAGO CPCm 40BD'),
('COMPRESSOR_DE_PARAFUSO', 'COMPRESSOR DE PARAFUSO'),
('COMPRESSOR_PISTÃO_SCHULZ', 'COMPRESSOR PISTÃO SCHULZ'),
('CONFORMADORA', 'CONFORMADORA'),
('CURVADORA', 'CURVADORA'),
('ENROLADOR_DE_FITA', 'ENROLADOR DE FITA'),
('ESMERIL', 'ESMERIL'),
('ESPULADEIRA', 'ESPULADEIRA'),
('ESTUFA_DE_FUNIL', 'ESTUFA DE FUNIL'),
('ESTUFA_ELETRICA', 'ESTUFA ELETRICA'),
('EXTRUSORA', 'EXTRUSORA'),
('EXTRUSORA_DE_PA', 'EXTRUSORA DE PA'),
('FORNO', 'FORNO'),
('FORNO_ELÉTRICO', 'FORNO ELÉTRICO'),
('FRESADORA_FERRAMENTARA', 'FRESADORA FERRAMENTARA'),
('GERADOR', 'GERADOR'),
('GUILHOTINA', 'GUILHOTINA'),
('JATO_DE_GRANALHA', 'JATO DE GRANALHA'),
('JATO_DE_OXIDO_DE_ALUMINIO', 'JATO DE OXIDO DE ALUMINIO'),
('LAVADOR_DE_PEÇAS', 'LAVADOR DE PEÇAS'),
('MAQUINA_A_LASER', 'MAQUINA A LASER'),
('MAQUINA_DE_CORRUGAR', 'MAQUINA DE CORRUGAR'),
('MAQUINA_DE_SOLDA', 'MAQUINA DE SOLDA'),
('MAQUINA_DE_TESTE', 'MAQUINA DE TESTE'),
('MAQUINA_DE_VIBRO', 'MAQUINA DE VIBRO'),
('MAQUINA_DE_VIROLA', 'MAQUINA DE VIROLA'),
('MISTURADOR', 'MISTURADOR'),
('MOLDAGEM_COM_GLICERINA', 'MOLDAGEM COM GLICERINA'),
('PLAINA', 'PLAINA'),
('POLICORTE', 'POLICORTE'),
('PRENSA', 'PRENSA'),
('PRENSA_DE_EIXO_EXCENTRICO', 'PRENSA DE EIXO EXCENTRICO'),
('PRENSA_DE_MOLDAGEM', 'PRENSA DE MOLDAGEM'),
('PRENSA_HIDRÁULICA', 'PRENSA HIDRÁULICA'),
('PRÉ-MOLDE', 'PRÉ-MOLDE'),
('PUXADOR', 'PUXADOR'),
('QUADRO_DE_FORÇA', 'QUADRO DE FORÇA'),
('QUADRO_DE_ILUMINAÇÃO', 'QUADRO DE ILUMINAÇÃO'),
('QUADRO_ELETRICO_ENGENHARIA', 'QUADRO ELETRICO ENGENHARIA'),
('QUADRO_ELETRICO_PORTARIA', 'QUADRO ELETRICO PORTARIA'),
('QUADRO_ELETRICO_REFEITÓRIO', 'QUADRO ELETRICO REFEITÓRIO'),
('QUADRO_GERAL_DO_AR_CONDICIONADO', 'QUADRO GERAL DO AR CONDICIONADO'),
('RECRAVADEIRA_DE_MANGUEIRAS', 'RECRAVADEIRA DE MANGUEIRAS'),
('RETIFICA_DEWALT', 'RETIFICA DEWALT'),
('ROUTER', 'ROUTER'),
('SERRA', 'SERRA'),
('SERRA_CIRCULAR', 'SERRA CIRCULAR'),
('SERRA_DE_FITA', 'SERRA DE FITA'),
('SOLDA_POR_INDUÇÃO', 'SOLDA POR INDUÇÃO'),
('TAMBOREADOR', 'TAMBOREADOR'),
('TESTE_TREFILA', 'TESTE TREFILA'),
('TORNO_AUTOMATICO', 'TORNO AUTOMATICO'),
('TORNO_AUTOMÁTICO', 'TORNO AUTOMÁTICO'),
('TORNO_CNC', 'TORNO CNC'),
('TORNO_MECANICO', 'TORNO MECANICO'),
('TORNO_REVOLVER', 'TORNO REVOLVER'),
('TORRE_DE_RESFRIAMENTO', 'TORRE DE RESFRIAMENTO'),
('TRANÇADEIRA', 'TRANÇADEIRA'),
('TREFILA', 'TREFILA'),
('TRIDIMENSIONAL', 'TRIDIMENSIONAL');
