
/* 
   SGMI 2.0 - SCRIPT DE IMPORTAÇÃO DE EQUIPAMENTOS (LISTA PDF FO-091)
   DATA: 09/06/2025 (Revisão 00)
   ALVO: Tabela equipment
*/

-- 1. LIMPEZA SEGURA (Remove dados antigos de equipamentos para reinserção limpa)
DELETE FROM work_orders; -- Necessário pois OS dependem de equipamentos
DELETE FROM equipment;

-- 2. INSERÇÃO EM LOTE
INSERT INTO equipment (id, name, manufacturer, model, year_of_manufacture, location, status, is_critical, category) VALUES
-- PÁGINA 1
('PH-15', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('CF-01', 'CÂMARA FRIA', 'ENGE FRIL', NULL, NULL, 'EXTRUSÃO', 'Ativo', false, 'Industrial'),
('TB-01', 'TAMBOREADOR', 'GV MÁQUINA', NULL, NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('FO-10', 'FORNO', NULL, NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('TA-01', 'TORNO AUTOMÁTICO', 'TRAUB', 'A15125', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TA-02', 'TORNO AUTOMÁTICO', 'TRAUB', 'A15125', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('AF-01', 'AUTOFRETAGEM', '-', '-', NULL, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('FO-09', 'FORNO ELÉTRICO', 'REVEST ARC', 'VC-091148', NULL, NULL, 'Ativo', true, 'Industrial'),
('TD-02', 'TRANÇADEIRA', 'NADOLSKY', NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('FO-11', 'FORNO', 'STANDARD', 'SET', 2002, NULL, 'Ativo', true, 'Industrial'),
('FO-12', 'FORNO', NULL, NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('TRID-01', 'TRIDIMENSIONAL', NULL, NULL, NULL, 'SALA QUALIDADE', 'Ativo', false, 'Industrial'),
('TF-01', 'TREFILA', NULL, NULL, NULL, 'TREFILA', 'Ativo', false, 'Industrial'),
('ES-01', 'ESMERIL', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('SF-03', 'SERRA DE FITA', 'RONEMAK', 'MR 330', NULL, NULL, 'Ativo', false, 'Industrial'),
('EX-01', 'EXTRUSORA', NULL, NULL, NULL, 'EXTRUSÃO', 'Ativo', true, 'Industrial'),
('AEX-01', 'EXTRUSORA DE PA', 'ATEMA', 'EX 60/30', 2021, 'AUTOMOTIVO', 'Ativo', true, 'Industrial'),
('AEX-02', 'EXTRUSORA DE PA', 'ATEMA', 'EX 60/30', 2021, 'AUTOMOTIVO', 'Ativo', true, 'Industrial'),
('MI-04', 'MISTURADOR', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('EX-02', 'EXTRUSORA', 'SAFETY SWITCH', NULL, NULL, 'EXTRUSÃO', 'Ativo', true, 'Industrial'),
('EX-03', 'EXTRUSORA', 'WK WOREK', 'D8555', 1992, 'EXTRUSÃO', 'Ativo', true, 'Industrial'),
('TA-03', 'TORNO AUTOMÁTICO', 'TRAUB', 'TA25', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('FO-13', 'FORNO', 'SHAMMATHERM', 'SH-T', 2013, NULL, 'Ativo', true, 'Industrial'),
('TF-02', 'TREFILA', 'LOMBARD', NULL, NULL, 'TREFILA', 'Ativo', false, 'Industrial'),
('FO-08', 'FORNO', NULL, NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('ES-04', 'ESMERIL', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('TC-01', 'TORNO CNC', 'NARDINI', 'L.195', 2009, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TC-02', 'TORNO CNC', 'NARDINI', 'L.195', 2009, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TC-03', 'TORNO CNC', 'NARDINI', 'L.195', 2004, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TC-04', 'TORNO CNC', 'NARDINI', 'L.195', 2006, 'USINAGEM', 'Ativo', false, 'Industrial'),
('JT-01', 'JATO DE GRANALHA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('TC-05', 'TORNO CNC', 'NARDINI', 'L.195', 2008, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TC-06', 'TORNO CNC', 'NARDINI', 'L.195', 2009, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TC-07', 'TORNO CNC', 'ROMI', 'CENTUR 30D', 2007, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TC-08', 'TORNO CNC', 'NARDINI', 'L.350', 2013, 'USINAGEM', 'Ativo', false, 'Industrial'),
('MS-01', 'MAQUINA DE SOLDA', NULL, NULL, NULL, 'DESATIVADA', 'Inativo', false, 'Industrial'),
('JT-02', 'JATO DE OXIDO DE ALUMINIO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('EX-05', 'EXTRUSORA', NULL, NULL, NULL, 'EXTRUSÃO', 'Ativo', true, 'Industrial'),
('EP-02', 'ESPULADEIRA', 'FUSOTEC', '72', 1997, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('FO-01', 'ESTUFA ELETRICA', 'TECHAIR', NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('FO-02', 'ESTUFA ELETRICA', 'SEANDARD', 'SE-T', 2003, NULL, 'Ativo', true, 'Industrial'),
('FO-03', 'FORNO', 'INCO', 'BTH3601485', NULL, NULL, 'Ativo', true, 'Industrial'),
('FO-04', 'FORNO', NULL, NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('FO-05', 'FORNO', NULL, NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('FO-06', 'FORNO', NULL, NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('FO-07', 'FORNO', NULL, NULL, NULL, NULL, 'Ativo', true, 'Industrial'),
('PH-01', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-03', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-02', 'PRENSA DE MOLDAGEM', 'EKA', NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-04', 'PRENSA HIDRÁULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('TD-03', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('TM-03', 'TORNO MECANICO', 'DIPLOMAT', 'ND.250', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TM-04', 'TORNO MECANICO', 'NARDINI', 'ND.250', 2013, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TM-05', 'TORNO MECANICO', 'NARDINI', 'ND.250', 2013, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TM-06', 'TORNO MECANICO', 'DIPLOMAT', 'NZ.400', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('MG-01', 'MOLDAGEM COM GLICERINA', NULL, NULL, NULL, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('PH-13', 'PRENSA HIDRAULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('ES-03', 'ESMERIL', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('PH-14', 'PRENSA', 'LP COPÉ', 'PHR 600', 1985, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-16', 'PRENSA HIDRAULICA', 'INCO', 'PC 30005385', NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-18', 'PRENSA HIDRAULICA', 'RANALLI', NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-19', 'PRENSA HIDRAULICA', 'FAREX', NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('TD-01', 'TRANÇADEIRA', 'FUSOTEC', 'W72', 2004, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('SF-01', 'SERRA', 'BALDAN', 'SFC-3', 2020, NULL, 'Ativo', false, 'Industrial'),

-- PÁGINA 2
('EX-04', 'EXTRUSORA', 'JENNINGS', NULL, NULL, 'EXTRUSÃO', 'Ativo', true, 'Industrial'),
('PH-20', 'PRENSA HIDRAULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-05', 'PRENSA DE EIXO EXCENTRICO', 'FABBE', NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-06', 'PRENSA HIDRAULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-07', 'PRENSA DE MOLDAGEM', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('MS-02', 'MAQUINA DE SOLDA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('MS-03', 'MAQUINA DE SOLDA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('MS-04', 'MAQUINA DE SOLDA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('CT-01', 'CENTRO DE USINAGEM', 'ROMI', 'DISCOVERYV1250', 2007, 'USINAGEM', 'Ativo', false, 'Industrial'),
('PH-08', 'PRENSA HIDRAULICA', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-09', 'PRENSA DE MOLDAGEM', NULL, NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-10', 'PRENSA DE MOLDAGEM', 'INCO', 'PC1502385', NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('TM-02', 'TORNO MECANICO', 'NARDINI', 'MS205', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('RE-01', 'RETIFICA DEWALT', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('PH-17', 'PRENSA DE MOLDAGEM', 'RANALLI', NULL, NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('SF-02', 'SERRA DE FITA', 'FRANHO', 'SH-4242NC', 2013, NULL, 'Ativo', false, 'Industrial'),
('PM-01', 'PRÉ-MOLDE', 'JENNINGS', NULL, NULL, 'MOLDAGEM', 'Ativo', false, 'Industrial'),
('TA-04', 'TORNO AUTOMÁTICO', 'TRAUB', 'A25', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TA-05', 'TORNO AUTOMÁTICO', 'ATRAS MÁQUINA', '15MM/25M', 2005, 'USINAGEM', 'Ativo', false, 'Industrial'),
('EP-01', 'ESPULADEIRA', 'FUSOTEC', 'W1/W72', 2014, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('EP-03', 'ESPULADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('PO-01', 'POLICORTE', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('TD-05', 'TRANÇADEIRA', 'FUSOTEC', 'W721A', 2011, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('EF-01', 'CONFORMADORA', 'CRIPPA', 'S2086', 2023, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('ML-01', 'MAQUINA A LASER', 'GALVO SCANNER', 'CMK-DESK-30', 2023, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('ML-02', 'MAQUINA A LASER', NULL, NULL, NULL, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('CO-01', 'COMPRESSOR CHICAGO CPCm 40BD', NULL, NULL, NULL, 'SALA DE MAQUINA', 'Ativo', true, 'Industrial'),
('TM-01', 'TORNO MECANICO', NULL, NULL, NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TS-01', 'MAQUINA DE TESTE', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('TD-06', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('CV-01', 'CURVADORA', 'CRIPPA', '1025E', 2024, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('RM-01', 'RECRAVADEIRA DE MANGUEIRAS', 'HYLIK', 'YB120L', 2023, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('CS-01', 'CABINE SECUNDARIA', NULL, NULL, NULL, 'SALA DE MAQUINA', 'Ativo', true, 'Industrial'),
('CPR-01', 'CABINE PRIMARIA', NULL, NULL, NULL, 'SALA DE MAQUINA', 'Ativo', true, 'Industrial'),
('QI-01', 'QUADRO DE ILUMINAÇÃO', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('QDF-05', 'QUADRO DE FORÇA', 'ALTOVOLT', NULL, 2021, NULL, 'Ativo', false, 'Predial'),
('QGC-01', 'QUADRO GERAL DO AR CONDICIONADO', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('FR-01', 'FRESADORA FERRAMENTARA', 'DIPLOMAT', '2000FVF', 2000, 'FERRAMENTARIA', 'Ativo', false, 'Industrial'),
('QDF-04', 'QUADRO DE FORÇA', 'ALTOVOLT', NULL, 2021, NULL, 'Ativo', false, 'Predial'),
('QDF-02', 'QUADRO DE FORÇA', 'ALTOVOLT', NULL, 2021, NULL, 'Ativo', false, 'Predial'),
('QDF-01', 'QUADRO DE FORÇA', 'ALTOVOLT', NULL, 2021, NULL, 'Ativo', false, 'Predial'),
('QDF-06', 'QUADRO DE FORÇA', 'ALTOVOLT', NULL, 2021, NULL, 'Ativo', false, 'Predial'),
('QE-01', 'QUADRO ELETRICO PORTARIA', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('QE-03', 'QUADRO ELETRICO ENGENHARIA', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('TD-04', 'TRANÇADEIRA', 'FUSOTEC', NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('QE-02', 'QUADRO ELETRICO REFEITÓRIO', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('CA-01', 'CALANDRA', NULL, NULL, NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('SI-01', 'SOLDA POR INDUÇÃO', 'GRC', 'WRG-15-10', NULL, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('MI-01', 'MISTURADOR', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('MI-02', 'MISTURADOR', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('MI-03', 'MISTURADOR', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('CH01', 'CHILLER', 'SMART-CHILLER', 'VAVO45A2PR', 2023, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('TF-04', 'TREFILA', NULL, NULL, NULL, 'TREFILA', 'Ativo', false, 'Industrial'),
('CR-02', 'MAQUINA DE CORRUGAR', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('TD-07', 'TRANÇADEIRA', 'FUSOTEC', 'W72TA', 2011, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('TD-08', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('BEB1', 'BEBEDOURO DIRETORIA', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('BEB2', 'BEBEDOURO ENGENHARIA', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('BEB5', 'BEBEDOURO AUTOMOTIVO', NULL, NULL, NULL, 'AUTOMOTIVO', 'Ativo', false, 'Predial'),
('BEB6', 'BEBEDOURO INJEÇÃO', NULL, NULL, NULL, NULL, 'Ativo', false, 'Predial'),
('CO-02', 'COMPRESSOR DE PARAFUSO', NULL, NULL, NULL, 'SALA DE MAQUINA', 'Ativo', true, 'Industrial'),
('CO-03', 'COMPRESSOR PISTÃO SCHULZ', NULL, NULL, NULL, 'SALA DE MAQUINA', 'Ativo', true, 'Industrial'),
('TF-03', 'TREFILA', NULL, NULL, NULL, 'TREFILA', 'Ativo', false, 'Industrial'),
('EN-01', 'ENROLADOR DE FITA', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),

-- PÁGINA 3
('FR-02', 'FRESADORA FERRAMENTARIA', NULL, NULL, NULL, 'FERRAMENTARIA', 'Ativo', false, 'Industrial'),
('CP-01', 'CABINE DE PINTURA HALAR', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('CP-02', 'CABINE DE PINTURA', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('TD-09', 'TRANÇADEIRA', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('PH-11', 'PRENSA HIDRAULICA', 'INCO', 'PC1503385', NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('PH-12', 'PRENSA HIDRAULICA', 'INCO', 'PC1504385', NULL, 'MOLDAGEM', 'Ativo', true, 'Industrial'),
('TES-01', 'TESTE TREFILA', NULL, NULL, NULL, 'TREFILA', 'Ativo', false, 'Industrial'),
('CR-01', 'MAQUINA DE CORRUGAR', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('TM-07', 'TORNO MECANICO', NULL, NULL, NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('PX-01', 'PUXADOR', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),
('CH-02', 'CHILLER', NULL, 'VAVO45A2PR201X', NULL, NULL, 'Ativo', false, 'Industrial'),
('TA-06', 'TORNO AUTOMATICO', 'TRAUB', 'TB-42', NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('TR-01', 'TORNO REVOLVER', 'ATRAS MÁQUINA', 'TR-25', 2005, 'USINAGEM', 'Ativo', false, 'Industrial'),
('RO-01', 'ROUTER', 'SCRIBA', 'SB1325TM', 2016, 'USINAGEM', 'Ativo', false, 'Industrial'),
('RO-02', 'ROUTER', 'ROCTECH', 'RO1525S-ATC-TM', 2022, 'USINAGEM', 'Ativo', false, 'Industrial'),
('VR-01', 'MAQUINA DE VIBRO', NULL, NULL, NULL, NULL, 'Ativo', false, 'Industrial'),

-- OBSOLETOS
('LP-02', 'LAVADOR DE PEÇAS', 'GV EQUIPAMENTOS', NULL, NULL, 'OBSOLETO', 'Inativo', false, 'Industrial'),
('PL-01', 'PLAINA', 'BALDAN', 'DPC-5', 2008, 'OBSOLETO', 'Inativo', false, 'Industrial'),
('BA-012', 'BALANÇA', 'TOLEDO', '2003/38-2180', 2014, 'OBSOLETO', 'Inativo', false, 'Industrial'),
('BA-010', 'BALANÇA', NULL, 'BCW30', 2013, 'OBSOLETO', 'Inativo', false, 'Industrial'),
('FO-14', 'FORNO', NULL, NULL, NULL, 'OBSOLETO', 'Inativo', false, 'Industrial'),

-- OUTROS
('CR-03', 'MAQUINA DE CORRUGAR', NULL, NULL, NULL, 'TRANÇADEIRA', 'Ativo', false, 'Industrial'),
('CT-02', 'CENTRO DE USINAGEM', NULL, NULL, NULL, 'USINAGEM', 'Ativo', false, 'Industrial'),
('ET-01', 'ESTUFA DE FUNIL', 'XIECHENG', 'XC-G100KG', 2025, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('MV-01', 'MAQUINA DE VIROLA', NULL, NULL, NULL, 'ENCAMISAMENTO', 'Ativo', false, 'Industrial'),
('GE-01', 'GERADOR', NULL, NULL, NULL, 'SALA DE MAQUINA', 'Ativo', true, 'Industrial'),
('SC-01', 'SERRA CIRCULAR', 'BERAT', '315B', NULL, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('TRA-01', 'TORRE DE RESFRIAMENTO', NULL, NULL, NULL, 'EXTRUSÃO', 'Ativo', false, 'Industrial'),
('CL-01', 'CAVALETE AR RESPIRATORIO', NULL, NULL, NULL, 'TUBULAÇÃO', 'Ativo', false, 'Industrial'),
('EX-06', 'EXTRUSORA', 'SUKO', 'PFG150 RAM', NULL, 'EXTRUSÃO', 'Ativo', true, 'Industrial'),
('EX-07', 'EXTRUSORA', 'SUKO', 'PFG150 RAM', NULL, 'EXTRUSÃO', 'Ativo', true, 'Industrial'),
('GUI-01', 'GUILHOTINA', 'POLIFLUOR', NULL, 2025, 'AUTOMOTIVO', 'Ativo', false, 'Industrial'),
('SF-04', 'SERRA DE FITA', 'MADA', 'SH - 500M', 2024, 'SOLDA', 'Ativo', false, 'Industrial');
